swapping home page with image upload feature
albfelix31/team-11-codeu pull request #26
Opened 2019-06-26 20:05 UTC by bstutenroth

2019-06-26 20:42 UTC, wayneb0t requested changes
The behavior here is kind of weird. Going to localhost:8080 loads index.html which is the image upload page rather than the landing page. It seems like you'd want to rename homepage.html to index.html and then rename the current index.html to something else like image-upload.html

Also, index.yaml is a configuration file used by Datastore and shouldn't be renamed

2019-06-26 20:44 UTC, wayneb0t commented on src/main/webapp/js/navigation-loader.js
> +              '/temp.html?user=' + loginStatus.username, 'feed'));
If this hasn't been implemented yet, you can just remove it. No need to keep a link around that doesn't work

2019-06-27 05:08 UTC, albfelix31 approved these changes
LGTM!

2019-06-27 06:59 UTC, wayneb0t approved these changes

2019-06-27 19:56 UTC, merged